### ISSUE TITLE
chore: create standard blob storage example

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-storage#105]
Create example where account kind is `BlobStorage` and account tier is `Standard`

**Comment by helenakallekleiv** [comment]
Closing this issue as this feature has been implemented in the merging of this PR #103.

**Comment by hknutsen** [comment]
@helenakallekleiv I don't think we actually have an example for standard blob storage in `examples` though 🤔

**Comment by helenakallekleiv** [comment]
@hknutsen My bad, I'll reopen and create an example 🙃
