### ISSUE TITLE
Threat protection is not compatible with subscriptions with new Defender for Storage Plan

### ISSUE THREAD

**Issue by ErlendT** [equinor/terraform-azurerm-storage#192]
Because "azurerm_advanced_threat_protection" is deploying "Defender for Storage (classic)", the deployment fails when the storage account is in a subscription with "new Defender for Storage". 

Maybe consider allowing disabling the creation of this resource?

It is also possible to move to the new plan for a single storage account, but this will create a dependency on the azapi provider https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-infrastructure-as-code-enablement?tabs=enable-storage-account#terraform-template

![image](https://github.com/equinor/terraform-azurerm-storage/assets/32453298/b989b01e-1f8b-49e7-a3ba-61656200f63b)

**Comment by hknutsen** [comment]
I think adding the ability to disable the classic plan is the best solution for now.

We can consider adding support for the new plan once it's available in the AzureRM provider.
