### ISSUE TITLE
Find actual minimum AzureRM version

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-storage#2]
Currently minimum AzureRM version is set to `2.31`:

https://github.com/equinor/terraform-azurerm-storage/blob/190f2e2c89a77797e0f764c6a3d5909d7af6aa83/versions.tf#L7

We do not actually know if this module works with this specified version, as Terraform always downloads the latest version available. Set `version = "2.31.0"` and run Go test to find out. If the Go test passes, then we can keep this as is. If the Go test fails, read the error message and find the version in the [AzureRM provider changelog](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG-v2.md) that fixes the issue.

When you find the minimum version `X.Y.Z` that works with this module, set `version = ">= X.Y.Z"`,

**Comment by sebastianlolv** [comment]
Go test passed: OK. Keeping the version as written in the issue.
