### ISSUE TITLE
feat: ensure default network access rule is set to deny (CKV_AZURE_35)

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-storage#91]
Guide: https://docs.bridgecrew.io/docs/set-default-network-access-rule-for-storage-accounts-to-deny

**Comment by sebastianlolv** [comment]
Should be already implemented but as a bool?

`  network_rules {
    default_action = length(var.firewall_ip_rules) == 0 ? "Allow" : "Deny"
    bypass         = ["AzureServices"]
    ip_rules       = var.firewall_ip_rules
  }
}`

**Comment by hknutsen** [comment]
Good spot.

You could try something similar to equinor/terraform-azurerm-key-vault#29 and see if that fixes it.

**Comment by sebastianlolv** [comment]
This can be closed as we have a different setup for network access rules?

**Comment by sebastianlolv** [comment]
Can this be closed as its outdated?
